# Generated by Django 6.0.2 on 2026-03-03 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_caseinfo_timelineevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfo',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_infos', to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='caseinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_infos', to=settings.AUTH_USER_MODEL),
        ),
    ]
