# Generated by Django 6.0.2 on 2026-04-09 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_topic_jurisdiction_to_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='data',
            field=models.JSONField(default=dict, help_text='Extracted case data (case_type, court_info, parties, summary, spotted_issues, resources). key_dates → Deadline model, action_items → ActionItem model.'),
        ),
        migrations.CreateModel(
            name='ActionItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('deadline', models.CharField(blank=True, max_length=50)),
                ('href', models.URLField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='chat.caseinfo')),
            ],
            options={
                'verbose_name': 'action item',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('date', models.CharField(help_text='Date as provided by LLM (YYYY-MM-DD or as stated)', max_length=50)),
                ('is_deadline', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='chat.caseinfo')),
            ],
            options={
                'ordering': ['date', 'label'],
            },
        ),
    ]
