# Generated by Django 6.0.2 on 2026-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_migrate_dates_and_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='deadline',
            name='reminder_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('upload', 'Document Upload'), ('summary', 'Chat Summary'), ('change', 'Case Info Change'), ('resolution', 'Resolution')], max_length=20),
        ),
    ]
