# Generated by Django 6.0 on 2025-12-24 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="chat_docume_search__9bab25_gin",
        ),
        migrations.RemoveField(
            model_name="document",
            name="search_vector",
        ),
    ]
