# Generated by Django 6.0.1 on 2026-01-20 21:48

import chat.agents.base
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_document_chat_docume_search__9bab25_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent',
            field=models.CharField(default='LitigantAssistantAgent', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='data',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'content': '', 'role': 'system'}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(typing.Annotated, (chat.agents.base.SystemMessage | chat.agents.base.UserMessage | chat.agents.base.AssistantMessage | chat.agents.base.ToolMessage, django_pydantic_field.compat.django.FieldInfoContainer(None, (), {'_complete': True, '_final': False, '_qualifiers': set(), 'discriminator': 'role'})))),
        ),
    ]
