# Generated by Django 6.0.1 on 2026-01-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_content_remove_message_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='agent',
        ),
    ]
