# Generated by Django 6.0.2 on 2026-04-07 20:59

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import litigant_portal.agents.base
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_caseinfo_chat_session_alter_caseinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='data',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'content': '', 'role': 'system'}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(typing.Annotated, (litigant_portal.agents.base.SystemMessage | litigant_portal.agents.base.UserMessage | litigant_portal.agents.base.AssistantMessage | litigant_portal.agents.base.ToolMessage, django_pydantic_field.compat.django.FieldInfoContainer(None, (), {'_complete': True, '_final': False, '_qualifiers': set(), 'discriminator': 'role'})))),
        ),
    ]
