# Generated by Django 6.0.2 on 2026-02-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatsession_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sources',
        ),
    ]
