"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def _read_secret(env_var: str) -> str | None:
    """Read a secret from a file path or fall back to env var.

    Checks <ENV_VAR>_FILE first (path to a file containing the secret),
    then falls back to <ENV_VAR> directly. This pattern works with:
    - Docker Compose secrets (/run/secrets/...)
    - Kubernetes secrets (mounted as files)
    - Plain env vars (local dev, CI)
    """
    file_path = os.environ.get(f"{env_var}_FILE")
    if file_path:
        path = Path(file_path)
        if path.is_file():
            return path.read_text().strip()
    return os.environ.get(env_var)


# SECURITY WARNING: keep the secret key used in production secret!
# Reads SECRET_KEY_FILE first (Docker/K8s secrets), then SECRET_KEY env var.
# In DEBUG mode, auto-generates a random key if neither is set.
SECRET_KEY = _read_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for development; set DEBUG=false in production
DEBUG = os.environ.get("DEBUG", "true").lower() not in ("false", "0")

if not SECRET_KEY:
    if DEBUG:
        from django.core.management.utils import get_random_secret_key

        SECRET_KEY = get_random_secret_key()
    else:
        raise ValueError("SECRET_KEY or SECRET_KEY_FILE is required")

# Parse ALLOWED_HOSTS from env (comma-separated), default to localhost in debug
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "").split(",")
    if h.strip()
] or (["localhost", "127.0.0.1", "0.0.0.0"] if DEBUG else [])

# Required for Django's debug context processor to expose 'debug' in templates
if DEBUG:
    # In DEBUG mode, treat all IPs as internal (for Docker networking)
    class AllIPs:
        def __contains__(self, item):
            return True

    INTERNAL_IPS = AllIPs()
else:
    INTERNAL_IPS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "django_cotton",
    "heroicons",
    # Local apps
    "portal",
    "litigant_portal",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "chat.middleware.AnonymousSessionKeyMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "portal.context_processors.toast_messages",
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Supports DATABASE_URL env var, falls back to SQLite for local development

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# SQLite: use IMMEDIATE transactions to prevent "database is locked" under Gunicorn
if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    DATABASES["default"]["OPTIONS"] = {
        "transaction_mode": "IMMEDIATE",
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", "English"),
    ("es", "Spanish"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL can be overridden for GitHub Pages (e.g., /litigant-portal/static/)
STATIC_URL = os.environ.get("STATIC_URL", "/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Use ManifestStaticFilesStorage in production for cache busting
# In development (DEBUG=True), Django uses the default storage
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }

# Django Cotton configuration
# Default: components in templates/cotton/ (e.g., <c-button> → templates/cotton/button.html)
COTTON_DIR = "cotton"

# Django Allauth configuration
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Allauth account settings
ACCOUNT_LOGIN_METHODS = {"email"}  # Email-based login (not username)
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]  # Required fields
ACCOUNT_EMAIL_VERIFICATION = "none"  # Disable email verification for now
ACCOUNT_LOGOUT_ON_GET = False  # Require POST for CSRF protection
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email backend (console for dev, configure SMTP for production)
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Content Security Policy (django-csp)
# https://django-csp.readthedocs.io/
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)  # Alpine.js served locally
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "blob:",
)  # data: for inline, blob: for camera
CSP_FONT_SRC = ("'self'", "data:")
CSP_CONNECT_SRC = ("'self'",)
# Alpine.js CSP build — no unsafe-eval needed

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Production security settings
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Trust origins that match ALLOWED_HOSTS over HTTPS
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS if host != "*"
    ]

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"


# AI Chat configuration
CHAT_ENABLED = os.environ.get("CHAT_ENABLED", "true").lower() == "true"
DEFAULT_CHAT_AGENT = os.environ.get(
    "DEFAULT_CHAT_AGENT", "LitigantAssistantAgent"
)

# Support OPENAI_API_KEY_FILE for Docker/K8s secrets.
# LiteLLM reads OPENAI_API_KEY from os.environ at call time,
# so we populate the env var here if a file path is provided.
_openai_key = _read_secret("OPENAI_API_KEY")
if _openai_key:
    os.environ.setdefault("OPENAI_API_KEY", _openai_key)
