"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    "django-insecure-q@e2_$5d-)84%24cq9+300e*m1jafs2(t2-)$-=g@0)+5o44vp"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "django_cotton",
    "django_vite",
    "pattern_library",
    # Local apps
    "portal",
    "litigant_portal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
                "pattern_library.loader_tags",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Django Vite configuration
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static"
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_DEV_SERVER_HOST = "localhost"
DJANGO_VITE_DEV_SERVER_PORT = 5173

# Django Cotton configuration
COTTON_DIR = "templates"

# Django Pattern Library configuration (required by storybook-django)
PATTERN_LIBRARY = {
    "SECTIONS": (
        ("atoms", ["atoms"]),
        ("molecules", ["molecules"]),
        ("organisms", ["organisms"]),
        ("layouts", ["layouts"]),
    ),
    "TEMPLATE_DIR": BASE_DIR / "templates",
    "TEMPLATE_SUFFIX": ".html",
    "BASE_TEMPLATE_NAMES": ["templates/base.html"],
}

# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Django Allauth configuration
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Content Security Policy (django-csp)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    # Vite dev server (development only)
    "http://localhost:5173" if DEBUG else None,
)
CSP_SCRIPT_SRC = tuple(filter(None, CSP_SCRIPT_SRC))

CSP_STYLE_SRC = (
    "'self'",
    # Vite dev server (development only)
    "http://localhost:5173" if DEBUG else None,
)
CSP_STYLE_SRC = tuple(filter(None, CSP_STYLE_SRC))

CSP_IMG_SRC = (
    "'self'",
    "data:",  # Allow data URIs for inline images
    "blob:",  # Allow blob URLs for camera/file uploads
)

CSP_FONT_SRC = (
    "'self'",
    "data:",  # Allow data URIs for fonts
)

CSP_CONNECT_SRC = (
    "'self'",
    # Vite dev server HMR (development only)
    "ws://localhost:5173" if DEBUG else None,
    "http://localhost:5173" if DEBUG else None,
)
CSP_CONNECT_SRC = tuple(filter(None, CSP_CONNECT_SRC))

# AlpineJS is CSP-compatible by default (no eval needed)
# No need for 'unsafe-eval' or 'unsafe-inline' for scripts

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
