# Generated by Django 6.0.6 on 2026-06-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatthread_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
