# Generated by Django 6.0.6 on 2026-07-14 14:49

import django.db.models.deletion
import litigant_portal.app.models.assistant
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chatmessage_num_tokens_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(db_index=True, default='user_chat', max_length=50),
        ),
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=litigant_portal.app.models.assistant.user_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('text_chars', models.PositiveBigIntegerField(blank=True, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='app.useridentity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
