# Generated by Django 6.0.6 on 2026-07-14 17:30

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import litigant_portal.agents.message_schema
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatthread_description_chatthread_thread_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='data',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'content': '', 'role': 'system'}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(typing.Annotated, (litigant_portal.agents.message_schema.SystemMessage | litigant_portal.agents.message_schema.UserMessage | litigant_portal.agents.message_schema.AssistantMessage | litigant_portal.agents.message_schema.ToolMessage | litigant_portal.agents.message_schema.MetaMessage, django_pydantic_field.compat.django.FieldInfoContainer(None, (), {'_complete': True, '_final': False, '_qualifiers': set(), 'discriminator': 'role'})))),
        ),
        migrations.AlterField(
            model_name='message',
            name='data',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'content': '', 'role': 'system'}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(typing.Annotated, (litigant_portal.agents.message_schema.SystemMessage | litigant_portal.agents.message_schema.UserMessage | litigant_portal.agents.message_schema.AssistantMessage | litigant_portal.agents.message_schema.ToolMessage | litigant_portal.agents.message_schema.MetaMessage, django_pydantic_field.compat.django.FieldInfoContainer(None, (), {'_complete': True, '_final': False, '_qualifiers': set(), 'discriminator': 'role'})))),
        ),
    ]
