# Generated by Django 6.0.6 on 2026-07-20 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chatmessage_meta_alter_chatmessage_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('jurisdiction_level', models.CharField(blank=True, choices=[('state', 'State'), ('county', 'County'), ('district', 'District'), ('federal', 'Federal'), ('tribal', 'Tribal')], max_length=16)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'U.S. Virgin Islands')], max_length=2)),
                ('official_url', models.URLField(blank=True)),
                ('official_resources_url', models.URLField(blank=True)),
                ('fast_model', models.CharField(blank=True, choices=[('OpenAI', [('openai/gpt-5-nano', 'GPT-5 Nano'), ('openai/gpt-5.4-mini', 'GPT-5.4 Mini'), ('openai/gpt-5.5', 'GPT-5.5')]), ('AWS Bedrock', [('bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0', 'Claude Haiku 4.5'), ('bedrock/us.anthropic.claude-sonnet-5', 'Claude Sonnet 5'), ('bedrock/us.anthropic.claude-opus-4-8', 'Claude Opus 4.8')])], max_length=128, null=True)),
                ('assistant_model', models.CharField(blank=True, choices=[('OpenAI', [('openai/gpt-5-nano', 'GPT-5 Nano'), ('openai/gpt-5.4-mini', 'GPT-5.4 Mini'), ('openai/gpt-5.5', 'GPT-5.5')]), ('AWS Bedrock', [('bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0', 'Claude Haiku 4.5'), ('bedrock/us.anthropic.claude-sonnet-5', 'Claude Sonnet 5'), ('bedrock/us.anthropic.claude-opus-4-8', 'Claude Opus 4.8')])], max_length=128, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active_site')],
            },
        ),
        migrations.CreateModel(
            name='SiteMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'site'), name='unique_site_membership')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('meta_description', models.TextField(blank=True)),
                ('prompts', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='app.site')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_topic_slug')],
            },
        ),
    ]
