# Generated by Django 6.0.6 on 2026-07-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_site_sitemembership_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitemmodel',
            name='case',
        ),
        migrations.RemoveField(
            model_name='caseinfo',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='caseinfo',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='case',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='case',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='ActionItemModel',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
        migrations.DeleteModel(
            name='CaseInfo',
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
