# Generated by Django 6.0.6 on 2026-07-28 16:45, then hand-extended:
# Site becomes a singleton. Any environment already carrying Site rows (the
# deleted seed_data command created one with a random uuid4 on every startup)
# has to be collapsed to a single row and moved onto the fixed SITE_ID before
# the check constraint can be added, or `migrate` aborts validating it.

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models

SITE_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")


def _prune_extra_sites(apps, schema_editor):
    """Keep one site — the active one (falling back to the oldest) — and
    cascade-delete the rest with their scoped children. Runs while
    ``active`` still exists, so before it is removed below."""
    Site = apps.get_model("app", "Site")
    sites = Site.objects.using(schema_editor.connection.alias)
    keeper = (
        sites.filter(active=True).first()
        or sites.order_by("created_at").first()
    )
    if keeper is None:
        return
    deleted, _ = sites.exclude(pk=keeper.pk).delete()
    # The cascade queues deferred FK trigger events on app_site, and
    # Postgres refuses to ALTER a table with those pending — which the
    # very next operation does. Flush them inside this transaction.
    if deleted and schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def _pin_site_pk(apps, schema_editor):
    """Move the surviving row onto the fixed singleton id. Ordering is
    load-bearing: this runs after every FK to Site is dropped, otherwise
    the update trips those foreign keys."""
    Site = apps.get_model("app", "Site")
    Site.objects.using(schema_editor.connection.alias).update(id=SITE_ID)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_actionitemmodel_case_and_more'),
    ]

    operations = [
        migrations.RunPython(_prune_extra_sites),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopicFlowDeadline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('offset_days', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('number', 'Number'), ('choice', 'Choice'), ('boolean', 'Boolean')], default='text', max_length=32)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowFieldGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='flow_forms/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowFormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_field', models.CharField(max_length=255)),
                ('template', models.TextField(blank=True)),
                ('checked_when', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='sitemembership',
            name='unique_site_membership',
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': [('manage_site', 'Can manage the site'), ('manage_developers', 'Can manage developer access')]},
        ),
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_active_site',
        ),
        migrations.RemoveConstraint(
            model_name='topic',
            name='unique_site_topic_slug',
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='app.topic'),
        ),
        migrations.AddField(
            model_name='topicflowanswer',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_answers', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='topicflowdeadline',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowdeadline',
            name='offset_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='app.topicflowfield'),
        ),
        migrations.AddField(
            model_name='topicflowanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.topicflowfield'),
        ),
        migrations.AddField(
            model_name='topicflowfieldgroup',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.topicflowfieldgroup'),
        ),
        migrations.AddField(
            model_name='topicflowform',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowformfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app.topicflowform'),
        ),
        migrations.AddField(
            model_name='topicflowlink',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowsection',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.topicflow'),
        ),
        migrations.RemoveField(
            model_name='sitemembership',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitemembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='site',
            name='active',
        ),
        migrations.RemoveField(
            model_name='site',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='site',
        ),
        migrations.RunPython(_pin_site_pk),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('id', uuid.UUID('00000000-0000-0000-0000-000000000001'))), name='single_site_row'),
        ),
        migrations.AddConstraint(
            model_name='topicflow',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='unique_topic_flow_slug'),
        ),
        migrations.AddConstraint(
            model_name='topicflowanswer',
            constraint=models.UniqueConstraint(fields=('identity', 'field'), name='unique_identity_flow_answer'),
        ),
        migrations.AddConstraint(
            model_name='topicflowfield',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('group', 'order'), name='unique_group_field_order'),
        ),
        migrations.AddConstraint(
            model_name='topicflowform',
            constraint=models.UniqueConstraint(fields=('flow', 'slug'), name='unique_topic_flow_form_slug'),
        ),
        migrations.DeleteModel(
            name='SiteMembership',
        ),
    ]
