# Generated by Django 6.0.6 on 2026-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_add_contact_resource_and_topic_flow_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="git_sha",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
