# Generated by Django 6.1 on 2026-08-19 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_contact_resource_and_topic_flow_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='forms/')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_field', models.CharField(max_length=255)),
                ('template', models.TextField(blank=True)),
                ('checked_when', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowFormCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals')], default='equals', max_length=32)),
                ('value', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowInterviewPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFlowInterviewVariable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('question', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('number', 'Number'), ('choice', 'Choice'), ('boolean', 'Boolean')], default='text', max_length=32)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('is_global', models.BooleanField(default=False)),
                ('asked_when_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VariableAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='topicflowanswer',
            name='unique_identity_flow_answer',
        ),
        migrations.RemoveConstraint(
            model_name='topicflowfield',
            name='unique_topic_flow_field_name',
        ),
        migrations.RemoveField(
            model_name='topicflowfieldgroup',
            name='flow',
        ),
        migrations.RemoveConstraint(
            model_name='topicflowform',
            name='unique_topic_flow_form_slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'U.S. Virgin Islands')], max_length=2),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.form'),
        ),
        migrations.AddField(
            model_name='topicflowformcondition',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_conditions', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowformcondition',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_conditions', to='app.form'),
        ),
        migrations.AddField(
            model_name='topicflowinterviewpage',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_pages', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflowinterviewvariable',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='app.topicflowinterviewpage'),
        ),
        migrations.AddField(
            model_name='variable',
            name='asked_when',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gated_variables', to='app.variable'),
        ),
        migrations.AddField(
            model_name='topicflowinterviewvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_placements', to='app.variable'),
        ),
        migrations.AddField(
            model_name='topicflowformcondition',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_conditions', to='app.variable'),
        ),
        migrations.AlterField(
            model_name='topicflowdeadline',
            name='offset_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='app.variable'),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_answers', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.variable'),
        ),
        migrations.RemoveField(
            model_name='topicflowanswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='topicflowanswer',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='topicflowfield',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='topicflowfield',
            name='group',
        ),
        migrations.RemoveField(
            model_name='topicflowform',
            name='flow',
        ),
        migrations.DeleteModel(
            name='TopicFlowFormField',
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.CheckConstraint(condition=models.Q(('asked_when__isnull', False), ('asked_when_value__isnull', True), _connector='OR'), name='variable_gate_value_requires_gate'),
        ),
        migrations.AddConstraint(
            model_name='topicflowinterviewvariable',
            constraint=models.UniqueConstraint(fields=('page', 'variable'), name='unique_interview_page_variable'),
        ),
        migrations.AddConstraint(
            model_name='topicflowformcondition',
            constraint=models.CheckConstraint(condition=models.Q(('variable__isnull', False), ('value__isnull', True), _connector='OR'), name='form_condition_value_requires_variable'),
        ),
        migrations.AddConstraint(
            model_name='variableanswer',
            constraint=models.UniqueConstraint(fields=('identity', 'variable'), name='unique_identity_variable_answer'),
        ),
        migrations.DeleteModel(
            name='TopicFlowAnswer',
        ),
        migrations.DeleteModel(
            name='TopicFlowField',
        ),
        migrations.DeleteModel(
            name='TopicFlowFieldGroup',
        ),
        migrations.DeleteModel(
            name='TopicFlowForm',
        ),
    ]
