# Generated by Django 6.1 on 2026-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_form_formfield_topicflowformcondition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="in_schema",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="default",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
