# Generated by Django 6.0.6 on 2026-08-23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_merge_20260824_1200"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptArtifact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("system_prompt", models.TextField()),
                (
                    "tool_schemas",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="prompt_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chat_messages",
                to="app.promptartifact",
            ),
        ),
    ]
