# Generated by Django 6.0.6 on 2026-08-25 19:48

import json

import django.db.models.deletion
from django.db import migrations, models


def _defaults_to_json(apps, schema_editor):
    """Re-encode each CharField default as JSON, so the column's cast to
    jsonb succeeds. Postgres rejects a bare '' (and any bare string) as
    json, which would fail the AlterField below on a populated table."""
    Variable = apps.get_model("app", "Variable")
    for pk, value in Variable.objects.values_list("pk", "default"):
        Variable.objects.filter(pk=pk).update(
            default=None if value in ("", None) else json.dumps(value)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_promptartifact_chatmessage_prompt_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="in_schema",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="default",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(_defaults_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="variable",
            name="default",
            field=models.JSONField(blank=True, null=True),
        ),
        # FormField checkboxes: the stringly checked_when CharField becomes
        # a typed (variable, value) pair plus a `checked` flag, mirroring
        # Variable.asked_when. No rows exist yet (only sync_corpus writes
        # them), so a plain swap loses nothing.
        migrations.RemoveField(
            model_name="formfield",
            name="checked_when",
        ),
        migrations.AddField(
            model_name="formfield",
            name="checked",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formfield",
            name="checked_when",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkbox_fields",
                to="app.variable",
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="checked_when_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("checked_when__isnull", False))
                    | models.Q(("checked_when_value__isnull", True))
                ),
                name="formfield_condition_value_requires_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("checked_when__isnull", True))
                    | models.Q(("checked_when_value__isnull", False))
                ),
                name="formfield_condition_requires_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("checked__isnull", True))
                    | models.Q(("checked_when__isnull", True))
                ),
                name="formfield_checked_or_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("template", ""))
                    | (
                        models.Q(("checked__isnull", True))
                        & models.Q(("checked_when__isnull", True))
                    )
                ),
                name="formfield_checkbox_takes_no_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form", "pdf_field"),
                name="formfield_pdf_field_unique_per_form",
            ),
        ),
    ]
