# Generated by Django 6.0.6 on 2026-09-23 00:27

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_bedrock_model_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.TextField()),
                ('body', models.TextField()),
                ('state', models.TextField(db_default='active', default='active')),
                ('first_sequence', models.BigIntegerField(blank=True, null=True)),
                ('last_sequence', models.BigIntegerField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_memory',
            },
        ),
        migrations.CreateModel(
            name='AgentMemorySource',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('locator', models.JSONField(db_default={}, default=dict)),
                ('locator_sha256', models.TextField()),
            ],
            options={
                'db_table': 'agent_memory_source',
            },
        ),
        migrations.CreateModel(
            name='AgentPrompt',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.TextField()),
                ('description', models.TextField(db_default='', default='')),
                ('metadata', models.JSONField(db_default={}, default=dict)),
                ('version', models.IntegerField()),
                ('body', models.TextField()),
                ('state', models.TextField(db_default='draft', default='draft')),
            ],
            options={
                'db_table': 'agent_prompt',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('request', models.JSONField()),
                ('configuration', models.JSONField()),
                ('state', models.TextField(db_default='queued', default='queued')),
                ('attempt', models.IntegerField(db_default=1, default=1)),
                ('lock_version', models.BigIntegerField(db_default=0, default=0)),
                ('pending_question', models.JSONField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, null=True)),
                ('request_key', models.TextField()),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('context_format_version', models.IntegerField(blank=True, null=True)),
                ('context_selected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_config', models.JSONField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, null=True)),
                ('recall_policy_snapshot', models.JSONField(blank=True, null=True)),
                ('manifest_sha256', models.TextField(blank=True, null=True)),
                ('checkpoint_sequence', models.BigIntegerField(db_default=0, default=0)),
                ('checkpoint_format_version', models.IntegerField(blank=True, null=True)),
                ('checkpoint_attempt', models.IntegerField(blank=True, null=True)),
                ('checkpoint_conversation_sequence', models.BigIntegerField(blank=True, null=True)),
                ('checkpoint_data', models.JSONField(blank=True, null=True)),
                ('checkpoint_redacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_run',
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('attempt', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('kind', models.TextField()),
                ('state', models.TextField(db_default='pending', default='pending')),
                ('operation_key', models.TextField()),
                ('input', models.JSONField()),
                ('output', models.JSONField(blank=True, null=True)),
                ('model_identifier', models.TextField(blank=True, null=True)),
                ('tool_name', models.TextField(blank=True, null=True)),
                ('tool_call_id', models.TextField(blank=True, null=True)),
                ('usage', models.JSONField(db_default={}, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.TextField(blank=True, null=True)),
                ('redacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_run_step',
            },
        ),
        migrations.CreateModel(
            name='CorpusDocument',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('enabled', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'app_corpus_document',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('slug', models.TextField()),
                ('name', models.TextField()),
                ('config', models.JSONField(db_default={}, default=dict)),
                ('enabled', models.BooleanField(db_default=True, default=True)),
                ('court_name', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('jurisdiction_level', models.CharField(blank=True, choices=[('state', 'State'), ('county', 'County'), ('district', 'District'), ('federal', 'Federal'), ('tribal', 'Tribal')], db_default='', default='', max_length=16)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'U.S. Virgin Islands')], db_default='', default='', max_length=2)),
                ('official_url', models.URLField(blank=True, db_default='', default='')),
                ('official_resources_url', models.URLField(blank=True, db_default='', default='')),
            ],
            options={
                'db_table': 'app_court',
            },
        ),
        migrations.CreateModel(
            name='CourtTopic',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('config', models.JSONField(db_default={}, default=dict)),
                ('enabled', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'app_court_topic',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner_kind', models.TextField()),
                ('key', models.TextField()),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('s3_bucket', models.TextField()),
                ('s3_key', models.TextField()),
                ('s3_object_version', models.TextField(blank=True, null=True)),
                ('sha256', models.TextField()),
                ('byte_size', models.BigIntegerField()),
                ('media_type', models.TextField()),
                ('original_filename', models.TextField(blank=True, null=True)),
                ('origin_url', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(db_default={}, default=dict)),
                ('state', models.TextField()),
                ('storage_state', models.TextField(db_default='available', default='available')),
                ('index_revision', models.IntegerField(db_default=0, default=0)),
                ('index_state', models.TextField(db_default='pending', default='pending')),
                ('parser_version', models.TextField(blank=True, null=True)),
                ('chunker_version', models.TextField(blank=True, null=True)),
                ('index_config', models.JSONField(db_default={}, default=dict)),
                ('extraction_ref', models.JSONField(blank=True, null=True)),
                ('embedding_provider', models.TextField(blank=True, null=True)),
                ('embedding_model', models.TextField(blank=True, null=True)),
                ('embedding_dimensions', models.IntegerField(blank=True, null=True)),
                ('embedding_config', models.JSONField(db_default={}, default=dict)),
                ('chunk_count', models.IntegerField(db_default=0, default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('index_error_code', models.TextField(blank=True, null=True)),
                ('index_invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('ordinal', models.IntegerField()),
                ('body', models.TextField()),
                ('locator', models.JSONField()),
                ('text_sha256', models.TextField()),
            ],
            options={
                'db_table': 'app_document_chunk',
            },
        ),
        migrations.CreateModel(
            name='FactEvidence',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('role', models.TextField()),
                ('locator', models.JSONField(db_default={}, default=dict)),
                ('locator_sha256', models.TextField()),
            ],
            options={
                'db_table': 'app_fact_evidence',
            },
        ),
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('invocation_type', models.CharField(max_length=32)),
                ('code_version', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'app_import_audit',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('title', models.TextField()),
                ('case_reference', models.TextField(blank=True, null=True)),
                ('state', models.TextField(db_default='open', default='open')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_matter',
            },
        ),
        migrations.CreateModel(
            name='MatterDocument',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('note', models.TextField(db_default='', default='')),
            ],
            options={
                'db_table': 'app_matter_document',
            },
        ),
        migrations.CreateModel(
            name='MatterProcedure',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('state', models.TextField(db_default='active', default='active')),
                ('started_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_matter_procedure',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'app_message_attachment',
            },
        ),
        migrations.CreateModel(
            name='PhaseDocument',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('purpose', models.TextField()),
                ('position', models.IntegerField()),
                ('condition', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_phase_document',
            },
        ),
        migrations.CreateModel(
            name='PhaseProgress',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid', output_field=models.UUIDField()), default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('state', models.TextField(db_default='not_started', default='not_started')),
                ('basis', models.JSONField(db_default={}, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_phase_progress',
            },
        ),
        migrations.RemoveConstraint(
            model_name='topicflow',
            name='unique_topic_flow_slug',
        ),
        migrations.RemoveConstraint(
            model_name='variableanswer',
            name='unique_identity_variable_answer',
        ),
        migrations.RemoveField(
            model_name='site',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='jurisdiction_level',
        ),
        migrations.RemoveField(
            model_name='site',
            name='official_resources_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='official_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='state',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context_state',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='item_kind',
            field=models.CharField(default='message', max_length=32),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='origin',
            field=models.CharField(default='framework', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='search_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='next_sequence',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='status',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.topic'),
        ),
        migrations.AddField(
            model_name='promptartifact',
            name='canonical_format',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='promptartifact',
            name='canonical_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='previous_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='published_by',
            field=models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='state',
            field=models.CharField(default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topicflowdeadline',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='app.topicflowinterviewpage'),
        ),
        migrations.AddField(
            model_name='topicflowinterviewpage',
            name='completion_criteria',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='topicflowinterviewpage',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topicflowinterviewpage',
            name='key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='topicflowinterviewvariable',
            name='condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicflowinterviewvariable',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='recall_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='recall_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='recall_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='variable',
            name='value_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='variable',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='confirmation_state',
            field=models.CharField(default='unconfirmed', max_length=16),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='evidence_kind',
            field=models.CharField(default='user_statement', max_length=32),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='observed_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='state',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.variableanswer'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Use snake_case.')]),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='variable_name_version'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='conversation',
            field=models.ForeignKey(blank=True, db_column='thread_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.chatthread'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentmemory'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='user',
            field=models.ForeignKey(db_column='identity_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='agentmemorysource',
            name='conversation_item',
            field=models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.chatmessage'),
        ),
        migrations.AddField(
            model_name='agentmemorysource',
            name='fact_assertion',
            field=models.ForeignKey(blank=True, db_column='answer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.variableanswer'),
        ),
        migrations.AddField(
            model_name='agentmemorysource',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentmemory'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentprompt'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='published_by',
            field=models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.chatthread'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='prompt_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_steps', to='app.promptartifact'),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='checkpoint_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrunstep'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='generated_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrunstep'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='run_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrunstep'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('slug',), name='app_court_unique_0'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.court'),
        ),
        migrations.AddField(
            model_name='site',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.court'),
        ),
        migrations.AddField(
            model_name='courttopic',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.court'),
        ),
        migrations.AddField(
            model_name='courttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.topic'),
        ),
        migrations.AddField(
            model_name='corpusdocument',
            name='court_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.courttopic'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='context_court_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.courttopic'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='court_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.courttopic'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='court_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.courttopic'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.court'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='published_by',
            field=models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='corpusdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='agentmemorysource',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='form',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.document'),
        ),
        migrations.AddField(
            model_name='userupload',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.document'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='conversation_item',
            field=models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.chatmessage'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='fact_assertion',
            field=models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.variableanswer'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='run_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrunstep'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='importaudit',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='document',
            name='import_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.importaudit'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='import_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.importaudit'),
        ),
        migrations.AddField(
            model_name='topicflow',
            name='import_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.importaudit'),
        ),
        migrations.AddConstraint(
            model_name='topicflow',
            constraint=models.UniqueConstraint(fields=('court_topic', 'slug', 'version'), name='topic_flow_court_slug_version'),
        ),
        migrations.AddField(
            model_name='matter',
            name='court_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.courttopic'),
        ),
        migrations.AddField(
            model_name='matter',
            name='user',
            field=models.ForeignKey(db_column='identity_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.useridentity'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.matter'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.matter'),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.matter'),
        ),
        migrations.AddConstraint(
            model_name='variableanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('invalidated_at__isnull', True), ('reviewed', True), ('state', 'active')), fields=('identity', 'matter', 'variable'), name='answer_current_reviewed', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='variableanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_state', 'confirmed'), ('reviewed', True)), models.Q(('reviewed', False), models.Q(('confirmation_state', 'confirmed'), _negated=True)), _connector='OR'), name='answer_review_confirmation'),
        ),
        migrations.AddField(
            model_name='matterdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='matterdocument',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.matter'),
        ),
        migrations.AddField(
            model_name='matterprocedure',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.matter'),
        ),
        migrations.AddField(
            model_name='matterprocedure',
            name='procedure',
            field=models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.topicflow'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='conversation_item',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.chatmessage'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='phasedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.document'),
        ),
        migrations.AddField(
            model_name='phasedocument',
            name='phase',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.topicflowinterviewpage'),
        ),
        migrations.AddField(
            model_name='phaseprogress',
            name='last_run_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.agentrunstep'),
        ),
        migrations.AddField(
            model_name='phaseprogress',
            name='matter_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.matterprocedure'),
        ),
        migrations.AddField(
            model_name='phaseprogress',
            name='phase',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.topicflowinterviewpage'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('run', 'attempt', 'sequence'), name='agent_run_step_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('run', 'attempt', 'operation_key'), name='agent_run_step_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('id', 'run'), name='agent_run_step_unique_2'),
        ),
        migrations.AddConstraint(
            model_name='courttopic',
            constraint=models.UniqueConstraint(fields=('court', 'topic'), name='app_court_topic_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='courttopic',
            constraint=models.UniqueConstraint(fields=('id', 'court', 'topic'), name='app_court_topic_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('conversation', 'request_key'), name='agent_run_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('id', 'conversation'), name='agent_run_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='corpusdocument',
            constraint=models.UniqueConstraint(fields=('court_topic', 'document'), name='app_corpus_document_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='agentmemorysource',
            constraint=models.UniqueConstraint(fields=('memory', 'conversation_item', 'fact_assertion', 'document', 'locator_sha256'), name='agent_memory_source_unique_0', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'ordinal'), name='app_document_chunk_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='factevidence',
            constraint=models.UniqueConstraint(fields=('fact_assertion', 'role', 'conversation_item', 'document', 'run_step', 'locator_sha256'), name='app_fact_evidence_unique_0', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('previous_version',), name='app_document_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('owner_kind', 'owner_court', 'owner_user', 'key', 'version'), name='app_document_unique_1', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('s3_bucket', 's3_key', 's3_object_version'), name='app_document_unique_2', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='agentprompt',
            constraint=models.UniqueConstraint(fields=('previous_version',), name='agent_prompt_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='agentprompt',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='agent_prompt_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.UniqueConstraint(fields=('id', 'user', 'court_topic'), name='app_matter_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.UniqueConstraint(fields=('id', 'user'), name='app_matter_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='matterdocument',
            constraint=models.UniqueConstraint(fields=('matter', 'document'), name='app_matter_document_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='matterprocedure',
            constraint=models.UniqueConstraint(fields=('matter', 'procedure'), name='app_matter_procedure_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(fields=('conversation_item', 'document'), name='app_message_attachment_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(fields=('conversation_item', 'position'), name='app_message_attachment_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='phasedocument',
            constraint=models.UniqueConstraint(fields=('phase', 'document', 'purpose'), name='app_phase_document_unique_0'),
        ),
        migrations.AddConstraint(
            model_name='phasedocument',
            constraint=models.UniqueConstraint(fields=('phase', 'position'), name='app_phase_document_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='phaseprogress',
            constraint=models.UniqueConstraint(fields=('matter_procedure', 'phase'), name='app_phase_progress_unique_0'),
        ),
    ]
